### ISSUE TITLE
UI Change: Move "Add a CoRE piston to the top of the page

### ISSUE THREAD

**Issue by Toy4Rick** [ady624/CoRE#10]
As the number of Pistons grow in the phone app, the option to add a new Piston keeps moving down the page.  Consider  moving the Add a CoRE piston option to the top and freeze it there

Thanks, Rick

**Comment by ady624** [comment]
Not sure that will be possible. The list as well as the add graphical elements are rendered by ST. I only add a single app input, it renders the list and the add piston:

app( name: "pistons", title: "Add a CoRE piston...", appName: "CoRE", namespace: "ady624", multiple: true)

Sorry...

**Comment by Toy4Rick** [comment]
No worries, just thought it would be helpful.  Thanks for responding :)

Rick
