### ISSUE TITLE
Possible Flash On/Off Interval Validation Bug

### ISSUE THREAD

**Issue by krlaframboise** [ady624/CoRE#14]
The Flash settings won't save unless the On and Off Intervals are >= 1000.

Anything under that probably wouldn't work so I'm assuming this isn't a bug, but you might want to either prompt the user for seconds and programmatically convert to milliseconds or mention the valid range in the input's label or description to make it less confusing for users.

Thanks.

**Comment by ady624** [comment]
Range should be 250-60000 ms. I will check.

**Comment by ady624** [comment]
Is this still an issue?

**Comment by krlaframboise** [comment]
The range validates correctly, but if it's possible, displaying that range would make things less confusing to the user.  Since everything is working the way it's supposed to, I'm closing this issue.
