### ISSUE TITLE
"Control" option in device list throws exception

### ISSUE THREAD

**Issue by krlaframboise** [ady624/CoRE#19]
When you go to select a device for an action, the second item under convenience is "Control", but tapping it displays a blank page with the error message "You are not authorized to perform the requested operations".  This happens on Android, I'm not sure about iOS

It's harmless, but it's been there for a while so I figured I should mention it.

**Comment by ady624** [comment]
Yeah, I noticed it too, glanced at it, and minded my own business after that. I'll fix it soon, thank you :)

**Comment by ady624** [comment]
Fixed, thank you
