### ISSUE TITLE
Small bug

### ISSUE THREAD

**Issue by Toy4Rick** [ady624/CoRE#20]
Hi Adrian,

Piston dashboard shows 1 Piston as paused, Run Time Statistics shows zero paused
![image](https://cloud.githubusercontent.com/assets/17329636/16169062/0c7cf3f0-34d5-11e6-9675-858840a26738.png)
![image](https://cloud.githubusercontent.com/assets/17329636/16169064/14f975a8-34d5-11e6-8aaa-37a373ca787e.png)

Rick

**Comment by ady624** [comment]
Fixed, thank you.
