### ISSUE TITLE
Fade not working

### ISSUE THREAD

**Issue by jonphob** [ady624/CoRE#23]
![image](https://cloud.githubusercontent.com/assets/17929216/16184669/208b2bd6-36b6-11e6-8fa4-3b3e1fff188f.png)
![image](https://cloud.githubusercontent.com/assets/17929216/16184670/267f18a4-36b6-11e6-8097-5bc9ac24baad.png)
![image](https://cloud.githubusercontent.com/assets/17929216/16184673/2ca9173e-36b6-11e6-9c7a-a50dc58ca57f.png)
![image](https://cloud.githubusercontent.com/assets/17929216/16184675/30de4dce-36b6-11e6-9db9-4062be24cc86.png)

**Comment by ady624** [comment]
Have you tried with the latest version? I think I fixed that in v0.0.09f

**Comment by ady624** [comment]
Please try with v0.1.101.20160620 - Beta M1 - Various bug fixes, removed the instant variable tasks introduced in v0.1.09e because they break anything like x = x + 1

Let me know, thank you

**Comment by jonphob** [comment]
Sorry missed 09f, thought i was up to date!! Will upgrade to 101 and let you know when i get home

**Comment by jonphob** [comment]
![image](https://cloud.githubusercontent.com/assets/17929216/16194690/c2c8fe00-36ed-11e6-9521-3a91a563bf06.png)

not at home, so cant actually view light, but get error above

**Comment by ady624** [comment]
Fixed in v0.1.102.20160620 - Beta M1 - Fixed a problem with fadeLevel. Missed an s on "params"...

Sorry about the trouble... please confirm it is working for you so I can close this issue.

**Comment by jonphob** [comment]
Looking at logs, it all seems to be running as it should! I'll double check when I'm actually at home but confident you can close!

**Comment by ady624** [comment]
Thank you, closing, just reopen it if there is still trouble... thank you.
