### ISSUE TITLE
Simple Piston with Time-Based Condition Not Executing

### ISSUE THREAD

**Issue by jammastercd** [ady624/CoRE#25]
I have a Simple piston that uses a time-based condition to turn on and off my furnace fan (time between 10:35 PM CDT and 5:35 AM CDT).  The piston isn't executing at the 5:35 AM CDT time.

**Comment by waynelian** [comment]
Based on my understanding from ady624's post, the between condition is inclusive for start and exclusive for end. For the condition you set, it will
- Execute once at 10:35:00pm
- Execute again at 5:34:59am

So 5:35am will not execute..

**Comment by ady624** [comment]
No, the time events are timed so that they cover both state changes. The second injected time event happens at 5:35am. Problem was fixed.
