### ISSUE TITLE
Error when using Ask Alexa capability

### ISSUE THREAD

**Issue by ryanraytx** [ady624/CoRE#28]
I'm getting the following errors when executing the following piston.

![image](https://cloud.githubusercontent.com/assets/16291146/16436989/72e4baba-3d68-11e6-880f-52dd2744ccf8.png)

![img_0578](https://cloud.githubusercontent.com/assets/16291146/16437023/ace45b94-3d68-11e6-9c0a-4623ae87f06c.PNG)

**Comment by ady624** [comment]
Can you please try with v0.1.113? Are you still getting the errors?

Thank you

**Comment by ryanraytx** [comment]
Just tested this and we are good.  Thanks for looking into this!

**Comment by ryanraytx** [comment]
![capture](https://cloud.githubusercontent.com/assets/16291146/16605833/40ac6166-42f8-11e6-85d7-292766596fb4.PNG)
Sorry closed prematurely.  I'm still seeing the issues.  Sorry tested the wrong piston.

**Comment by ady624** [comment]
Ok, will try and replicate it. Thank you

**Comment by ady624** [comment]
Can you please try and see if the problem still exists in v0.1.12b?

**Comment by ryanraytx** [comment]
I will give it a try tonight...

**Comment by ryanraytx** [comment]
Sorry for the delay, I checked this last night and we are good.  Thanks for
the hard work on this and continued support!

**Comment by ady624** [comment]
Thank you, closing this.
