### ISSUE TITLE
Trigger "stays" not working under certain circonstances

### ISSUE THREAD

**Issue by amegn1000** [ady624/CoRE#29]
@ady624 

Hi,

As requested, I am replying with my issue on GitHub.

The trigger "stays" seems to be working under "IF" but not under "OR IF", "ELSE IF"...

Please see screenshot below:

https://1drv.ms/i/s!AjRjK_1unBAzlgQVIhN1PIcRMhAD

Under "OR-IF", the trigger "stays" is not firing the "When true..." or "THEN..."
I can see countdown, but then it goes under and "over due" or "past due" until it resets and does not execute conditional actions...

Thank you for your support!

**Comment by ady624** [comment]
Can you please try with a much simpler piston? Just a simple OR-IF, and keep with one device for the "stays" trigger. Then try using several devices. The "several" devices means CoRE will keep separate timers for each device and each device will trigger when its time elapsed.

**Comment by amegn1000** [comment]
Ady624,

I actually tried and made various test with much simpler OR-IF, using only 1 device for the "stays". It is not working for me...

The variable "stays" seems to be working under the IF part but not OR-IF...

Please let me know.

Many thanks, you rock!

Best regards,
Arnaud

**Comment by amegn1000** [comment]
Ady624,

Here is another example of a piston not working, this one is using only one device for "stays":

https://graph.api.smartthings.com/api/token/dd97eb06-51d1-40fd-b642-4421831ea26b/smartapps/installations/c6abf153-fa6e-45c7-9da5-9b2014ecde24/dashboard#/

Best regards,
Arnaud

**Comment by amegn1000** [comment]
Sorry,

Here is the exact link of the other piston using "stays" not working:

https://graph.api.smartthings.com/api/token/dd97eb06-51d1-40fd-b642-4421831ea26b/smartapps/installations/c6abf153-fa6e-45c7-9da5-9b2014ecde24/dashboard#/

Best regards,
Arnaud

**Comment by amegn1000** [comment]
It looks like I cannot point the actual piston.

Please refer to the piston "Entry Lighting"

Thank you! Sorry again about my confusing messages...

Best regards,
Arnaud

**Comment by amegn1000** [comment]
Awsomejob, after testing for a couple days now, "stays" is completely fixed!!!
