### ISSUE TITLE
All switches OFF restriction

### ISSUE THREAD

**Issue by Luvien** [ady624/CoRE#32]
Hello!
For my test purpose, I created a simulated virtual switch.  I created a simple piston 👍 

IF motion changes to active
THEN
Turn on light
ELSE
wait 3 mins
Turn off light

Restriction : Execute only when all switch OFF (my simulated switch).

Result : When I enter the room, the light goes on...
I tried 'Prevent already scedule task...' but it's not working.  When I turn on the switch, I'm not in the room.

**Comment by ady624** [comment]
What was the status of the virtual switch when the light turned on? Was it off?

**Comment by Luvien** [comment]
No, ON, I checked to be sure. I'm sure it doesnt change anything, but my light is on a Z-Wave dimmer.  I don't use setlevel or anything, only ON and OFF.

**Comment by ady624** [comment]
Just tested with one switch in the OFF restriction, v0.1.114.20160706 - Beta M1 - Some more minor bug fixes, including some piston restriction fixes

Switch off, light changed colors. Switch on, light no longer changing color.

Please confirm and close if found to be working.

**Comment by Luvien** [comment]
You nailed it. I tested multiple time today and it's working with the new version you provided.
Thanks!
