### ISSUE TITLE
Set Variable Done Button: Please fill the all required fields Error

### ISSUE THREAD

**Issue by nicholaswilde** [ady624/CoRE#35]
When pressing the _Done_ button on the _Set variable_ task menu, the **Please fill out all required fields** error is shown.

Platform: Android
SmartThings version: 2.1.5
Build Number: 204791

![image](https://cloud.githubusercontent.com/assets/600019/16631905/649e37ce-4376-11e6-8500-e80d461a4b39.png)
![image](https://cloud.githubusercontent.com/assets/600019/16631588/bcc21f4e-4374-11e6-9cb3-94a9f0c8d98c.png)

**Comment by ady624** [comment]
This is a known Android UI issue - iOS does not experience this issue, tap Done again or use < to exit.
