### ISSUE TITLE
Sonos "Adjust level" when grouped

### ISSUE THREAD

**Issue by amegn1000** [ady624/CoRE#38]
When using the action "Adjust level" with grouped Sonos for a single speaker, the volume will be adjusted by the piston for all the speakers.
The initial trigger increases the volume or decreases the volume a lot more than the expected value for all the speakers, then the next triggers will increase / decrease the volume with the correct value but for all the grouped speakers.

Please see below.

Log Trace:

7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:46:02 PM: trace ╔═══ Task processing took 926ms
7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:46:02 PM: trace ║░░░ Removing any existing ST safety nets
7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:46:02 PM: info ║░░░ Executing virtual command adjustLevel (839ms)
7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:46:01 PM: trace ║░░░ Installing ST safety net
7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:46:01 PM: trace ║░░░ Rescheduling time triggers
7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:46:01 PM: trace ╚═══ Processing tasks (v0.1.119.20160714)
7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:46:01 PM: trace ╔═══ Event processing took 74ms
7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:46:01 PM: info ║░░░ ♦ Basic Piston changed state to true ♦
7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:46:01 PM: trace ╚═══ Processing event switch for device Dining Room Dimmer Switch with id d5238591-3d96-402a-9f5a-f6236ee1ab96, value on, generated on Sat Jul 16 01:46:00 UTC 2016, about 714ms ago (v0.1.119.20160714)

Log Debug:

7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:47:52 PM: debug ╔═══ Done in 750ms
7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:47:52 PM: info ║░░░ Executing virtual command adjustLevel (481ms)
7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:47:51 PM: debug ║░░░ Processing command task [taskId:1, time:1468633671866, idx:1, marker:1468633671928, created:1468633671906, ownerId:1, data:[p:[[d:5, t:number, i:0]]], type:cmd, deviceId:546656ff-29e0-4551-9c39-bd196821bfd8]
7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:47:51 PM: debug ║░░░ Found 1 task due at this time
7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:47:51 PM: debug ║░░░ Scheduling actions for condition #0. State did change.
7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:47:51 PM: info ║░░░ ♦ Basic Piston changed state to true ♦
7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:47:51 PM: debug ║░░░ Primary IF block evaluation result is true
7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:47:51 PM: debug ║░░░ Scheduling actions for condition #1. State did change.
7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:47:51 PM: debug ║░░░ Setting non-matching device list to []
7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:47:51 PM: debug ║░░░ Setting matching device list to []
7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:47:51 PM: debug ║░░░ ♣ Function eval_trg_changes_to for Dining Room Dimmer Switch's switch [on] changes to 'on' returned true
7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:47:51 PM: debug ║░░░ Event eligibility for the primary IF block is 2 - ELIGIBLE (triggers required, event is a trigger)
7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:47:51 PM: debug ╚═══ Received a primary block device event
7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:47:48 PM: debug ╔═══ Done in 213ms
7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:47:48 PM: debug ║░░░ Scheduling actions for condition #-1. State did change.
7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:47:48 PM: info ║░░░ ♦ Basic Piston changed state to false ♦
7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:47:48 PM: debug ║░░░ Primary IF block evaluation result is false
7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:47:48 PM: debug ║░░░ Scheduling actions for condition #1. State did NOT change.
7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:47:48 PM: debug ║░░░ Setting non-matching device list to []
7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:47:48 PM: debug ║░░░ Setting matching device list to []
7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:47:48 PM: debug ║░░░ ♠ Function eval_trg_changes_to for Dining Room Dimmer Switch's switch [off] changes to 'on' returned false
7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:47:47 PM: debug ║░░░ Event eligibility for the primary IF block is 2 - ELIGIBLE (triggers required, event is a trigger)
7046db9c-f7ee-4cbe-ab02-3bdc2c05bf28  9:47:47 PM: debug ╚═══ Received a primary block device event

Let me know...

**Comment by ady624** [comment]
Could it be an issue with the Sonos integration? It appears only one adjustment is made. Another problem that may occur is if the current level value in ST does not really match the Sonos speaker's level. Can you try adjusting the Sonos from its physical buttons and confirm that the level changes in ST?
