### ISSUE TITLE
Problem / error with "Interaction" "Physical"

### ISSUE THREAD

**Issue by amegn1000** [ady624/CoRE#39]
When using "Trigger" using "Comparison" "Changes to" + "Value" "on"  + "Interaction" "Physical", piston is not triggering actions.

I get the following error:

babb4c21-cfda-4b3e-aaca-eea07bc3a08b  10:28:00 AM: error ║ ERROR: Error evaluating condition: java.lang.NullPointerException: Cannot get property 'physical' on null object
babb4c21-cfda-4b3e-aaca-eea07bc3a08b  10:27:58 AM: debug ║ ♣ Function eval_cond_is_one_of for Home's mode [Morning] is one of '[Awake, Morning]' returned true
babb4c21-cfda-4b3e-aaca-eea07bc3a08b  10:27:58 AM: error ║ ERROR: Error evaluating condition: java.lang.NullPointerException: Cannot get property 'physical' on null object
babb4c21-cfda-4b3e-aaca-eea07bc3a08b  10:27:58 AM: debug ║ ♠ Function eval_cond_is_less_than for Kitchen Multisensor's illuminance [288] is less than '60' returned false
babb4c21-cfda-4b3e-aaca-eea07bc3a08b  10:27:43 AM: debug ║ ♣ Function eval_cond_is_one_of for Home's mode [Morning] is one of '[Awake, Morning]' returned true
babb4c21-cfda-4b3e-aaca-eea07bc3a08b  10:27:43 AM: error ║ ERROR: Error evaluating condition: java.lang.NullPointerException: Cannot get property 'physical' on null object

Just to confirm i have physical switches selected in that case.

Thank you for the support!

**Comment by ady624** [comment]
Can you please confirm the switch DTH is actually reporting the physical activity? Look up the event in the Location section of the IDE. Not all devices correctly provide physical push information...

**Comment by amegn1000** [comment]
Thank,

Here is what I have:

![untitled](https://cloud.githubusercontent.com/assets/8299491/17267253/8d3a4880-55d2-11e6-8062-c1895da16572.png)

It looks like no interaction type is registered. Should I use a different DTH?

Thanks again.

Best regards,
Arnaud

**Comment by ady624** [comment]
Yes, you need to find a DTH that sends the isPhysical correctly.

If it's z-wave, try this: https://community.smartthings.com/t/release-z-wave-dimmer-switch-with-stepper-and-low-med-high/48183
