### ISSUE TITLE
Music player capabilities

### ISSUE THREAD

**Issue by TheFuzz4** [ady624/CoRE#4]
When selecting a music player i.e. Kodi I have to manually type in the condition.  If you need help with this please reach out to JoshLyon since he wrote the Kodi device handler.

**Comment by ady624** [comment]
Music player commands are not yet working as I have not yet figured out the parameters. Will fix in a future release.

**Comment by TheFuzz4** [comment]
No problems thanks for everything that you're doing and if you need a beta
tester for the kodi let me know.

**Comment by ady624** [comment]
Can you please list the methods that need work and their parameters? Be specific please, parameter name, type (string, boolean, number, decimal, enumeration) and range if any.

Thank you.

**Comment by TheFuzz4** [comment]
I will do my best to be specific with this but as I don't know much it might be vague.  I'll also ask Josh to add in if he can
As far as I can tell they're all string
Playing
Paused
Stopped

**Comment by TheFuzz4** [comment]
So I went into the code for the Kodi Device Handler is this what you're looking for?

```
        attributeState("paused", label:'Paused', icon: "st.sonos.pause-btn", backgroundColor:"#ffffff")
        attributeState("playing", label:'Playing', icon: "st.sonos.play-btn", backgroundColor:"#79b821")
        attributeState("stopped", label:'Stopped', icon: "st.sonos.stop-btn", backgroundColor:"#ffffff")
```

**Comment by ady624** [comment]
Can you please list the commands that need to be implemented and their parameters? Thank you

**Comment by ady624** [comment]
Wait, I just realized, are we talking about a custom attribute that you want supported? You can use the custom attribute, or I can see with JoshLyon if he wants to add a little piece of code for CoRE to "learn" that attribute...

**Comment by TheFuzz4** [comment]
I think that Josh would be the best solution for this.  I messaged him but haven't heard back from him.  Sorry was up camping all weekend so just got time to reply to this :)

**Comment by joshualyon** [comment]
There shouldn't be any code needed to be added to the Kodi DTH. Your SmartApp can use introspection for pulling in custom commands and attributes for a Device. That being said, the Kodi DTH mostly implements standard `Music Player` and `Media Controller` commands and attributes.

You can find the full list documented here:
https://github.com/iamcanadian2222/ST-Kodi/blob/master/CAPABILITIES.md

**Comment by TheFuzz4** [comment]
Thanks Josh for commenting on this :)

**Comment by TheFuzz4** [comment]
So I managed to accomplish what I wanted by manually putting in the status for playing, paused and stopped in the value field.  So I'm sure those are at least the values that we need to accomplish this.

**Comment by ady624** [comment]
I cannot have the status as an enumeration of the three, as the documentation for ST says it's a string - so I have to leave it open for the user to type in the name. Like I said, if Kodi would "describe" the attribute, then I can show a list instead of asking the user to type in the status. Without that, I can't go outside of the documentation and you just have to type in the status - not a big deal, I think?

**Comment by ady624** [comment]
As for what Josh is saying, I have been doing that from get-go. I think what the OP wants is a way to select one of the three statuses rather than typing them in - which requires the DTH to expose the possible values. It is not mandatory though, without this piece of information, the user can still simply type in a string value to match against. It's all about comfort, not functionality :)

**Comment by joshualyon** [comment]
> as the documentation for ST says it's a string

Fair point. The Music Player implementations I've seen have `playing`, `paused` and `stopped` but you're right that it's technically a STRING attribute so other DTHs may interpret and implement this differently. Officially, the ST documentation only allows the use of `possibleValues` with ENUM data types, so I agree with your approach of having users enter in the values for STRING data types.

**Comment by TheFuzz4** [comment]
Yeah we can close this out.  I don't have a problem with the manual typing in of the value.  Thanks Josh and Adrian for your help with this.
