### ISSUE TITLE
CarbonDioxide Support

### ISSUE THREAD

**Issue by bridaus** [ady624/CoRE#42]
For some reason CoRE does not pick up my Netatmo device for CarbonDioxide.  It says "you can't currently add this".

Netatmo device here: https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/6ac174c2f3ef5bf3bd598076c62a88dd9519ca64/devicetypes/dianoga/netatmo-basestation.src/netatmo-basestation.groovy

ST documentation here:  http://docs.smartthings.com/en/latest/capabilities-reference.html?highlight=water#carbon-dioxide-measurement

At first I thought it was a data type mismatch (docs say number, DTH says text, CoRE looks for decimal) but I know groovy usually handles that.

At a loss, let me know if I can try anything (@bridaus on community).

thanks!

**Comment by ady624** [comment]
You need to add the

`capability "Carbon Dioxide Measurement"`

to the DTH... it won't show in the list until it has that capability declared. It's not CoRE, it's how ST works, the ST UI builds the list and says "you can't currently add this" if it finds no device with that capability.
