### ISSUE TITLE
Cannot Open Existing Pistons, Add a CoRE piston or Settings

### ISSUE THREAD

**Issue by omayhemo** [ady624/CoRE#47]
v0.2.145.20160822
This started just today.  I pulled latest and published it to no affect.  I've been using this app for about a week and haven't had this problem.  Suddenly today, I went to update a piston and found when I click on a piston in CoRE I get the spinning icon for a couple seconds and then it simply goes away.  I can no longer open my existing pistons, add pistons, or open the settings.  Global variables and statistics work fine, however.

**Comment by CrustyAvocado** [comment]
Same problem here. Cannot add or edit pistons. CoRE Dashboard shows everything is off (even though it was on last time I checked and I didn't turn anything off). At this time CoRE is completely broken.

**Comment by omayhemo** [comment]
Well. It cleared itself up. No idea what happened. I reboot the hub but it continued not working for another hour there after. I happen to be compulsive so I just kept checking. Eventually the problem resolved.

**Comment by CrustyAvocado** [comment]
Same. Weird.

**Comment by ady624** [comment]
I believe that was a major issue with SmartThings where they lost a lot of states. CoRE fixed itself once the state eating bug was fixed by ST.
