### ISSUE TITLE
CoRE unable to execute / call routines

### ISSUE THREAD

**Issue by an39511** [ady624/CoRE#48]
Problem resolved by SmartThings.

**Comment by an39511** [comment]
Hi there,

Thank you for reaching out!

I am very sorry to hear you are running into this issue. This is a bug on our end that we are actively working on resolving as quickly as possible. I have tagged your email address so we can follow up with you as soon as a fix has been deployed. If there is anything else we can assist with in the meantime, please let us know!

Thank you for your patience with us through this and we'll talk to you soon.

Elliot
Support Engineer
SmartThings Support

**Comment by ady624** [comment]
Pfew :) thank you
