### ISSUE TITLE
java.lang.NullPointerException: Cannot get property 'app' on null object @ line 8355

### ISSUE THREAD

**Issue by jec2337** [ady624/CoRE#52]
Anytime I attempt to hit Done within a new or current Piston, or leaving the CoRE smart app, I get an error that pops up tin eh app `An unexpected error error occurred`.  The logs within IDE spit this one out `java.lang.NullPointerException: Cannot get property 'app' on null object @ line 8355`.  It has been working without issues and just one day stopped in recent weeks and finally had time to try to debug further.  The pistons that are running still work, but creation of new pistons will not work because of the incompletion of the save of the piston with the Done.  I get the same issue when trying to remove a piston or even attempting to completely remove CoRE.  Let me know what other info I can provide to help with my issue.

**Comment by ady624** [comment]
What version are we talking about?

**Comment by jec2337** [comment]
v0.3.157.20160928

**Comment by pianomansam** [comment]
I'm also seeing this error when trying to when trying to add a new Piston. Then I tried removing the app and received the error again and the app couldn't be removed.

**Comment by ady624** [comment]
Try with v0.3.158 please

**Comment by jec2337** [comment]
That fixed me!  I appreciate the quick turn around.  Always thinking of new things to do with your app, so definitely appreciate your contribution to the community.

**Comment by pianomansam** [comment]
This also fixed it for me but now I have another error stopping me from adding pistons.

#53
