### ISSUE TITLE
Follow-up piston got fired right away despite delay (1min) set

### ISSUE THREAD

**Issue by zennytan** [ady624/CoRE#61]
Follow-up piston got fired right away despite delay (1min) set.

I also set a SMS notification for debugging to ensure that it is indeed fired without any delay.

**Comment by zennytan** [comment]
![image](https://cloud.githubusercontent.com/assets/6257194/21148294/b5604c84-c192-11e6-8b79-280068527c19.png)

![image](https://cloud.githubusercontent.com/assets/6257194/21148344/d4efbc56-c192-11e6-9b04-07d249826720.png)

**Comment by idpaterson** [comment]
It looks like your follow up piston is not actually a "Follow-Up" piston but rather a "Basic" if/else. When the sensor switches to open your second piston is firing immediately. If you instead change its mode to Follow-Up it can only be triggered from other pistons.

This situation could be represented in a single piston unless you've organized it this way for reuse of the turn light off routine. If the contact sensor *stays open* for 1 minute and motion is inactive then turn off and send SMS.

**Comment by zennytan** [comment]
I am so sorry! You're da man! I played around for too much and missed out the most crucial part.. Setting it to "FOLLOW-UP PISTON"!

I will try again now, thank you!

**Comment by zennytan** [comment]
Thank you thank you thank you! It's working as intended :D

**Comment by idpaterson** [comment]
That's good, you can get assistance with CoRE [in the SmartThings forums](https://community.smartthings.com/t/core-get-peer-assistance-here-with-setting-up-pistons/50187). In my case I usually misunderstand what the logic is intended to do and someone over there can point me in the right direction to avoid filing a bug report in GitHub.
