### ISSUE TITLE
java.lang.NullPointerException @ line 8691

### ISSUE THREAD

**Issue by ertanden** [ady624/CoRE#62]
I just installed CoRE from the latest master branch and tried to add a simple Piston with motion sensor turning on a Philips Hue lamp. 

However when I press on "Done" for final step to add the piston, I get "Error Saving page" and the log says:

java.lang.NullPointerException @ line 8691

**Comment by paul-wade** [comment]
Same error message for me and scenario. My log shows a null at 8631 in the formatLocalTime function. Of course I don't know groovy but it's not that dissimilar to other languages. I have no idea how to debug to see what the actual values are though.

**Comment by paul-wade** [comment]
Ok that wasn't so hard. I added some logging to help me track down what was null. 
	def formatter = new java.text.SimpleDateFormat(format)
    log.warn "formatter is ${formatter}"
    log.warn "location is ${location.timeZone}"
	formatter.setTimeZone(location.timeZone)
	return formatter.format(time)

location was null. Duh. Went into the st app and changed settings on my location. I had never setup where the device is.

All is working now.

**Comment by ady624** [comment]
thanks
