### ISSUE TITLE
Possible UI change

### ISSUE THREAD

**Issue by jonphob** [ady624/CoRE#7]
![img_1220](https://cloud.githubusercontent.com/assets/17929216/15409017/dea65cb8-1e0a-11e6-88a4-be104c10f730.PNG)

Not sure if possible, but the 2 'then' actions run in different modes.
Is there anyway to show the modes they are restricted to without having to drill down into the next level?

Not a major issue but would be quicker when looking over pistons to make sure all things are set as I want them to be

**Comment by ady624** [comment]
Sure thing, it is nlt yet finished. The commands themselves need to be converted to plain English too. Will leave issue open until resolved.

**Comment by ady624** [comment]
Fixed as of v0.0.038.20160520 - Alpha test version - Displaying individual actions (when true) in the main piston page and showing action restrictions as per https://github.com/ady624/CoRE/issues/7
