### ISSUE TITLE
Unable to complete a Piston

### ISSUE THREAD

**Issue by r34220** [ady624/CoRE#79]
When selecting  "if" to add a condition, the next screen only shows the "Man Condition Group" header with nothing else.

What could be the issue? I have setup about 20 other pistons without any issue.

**Comment by idpaterson** [comment]
There was an update to fix this, please pull the latest from GitHub. SmartThings performed a major platform upgrade earlier this week which rendered CoRE and many other smart apps incompatible.

**Comment by Johnnyk56791234** [comment]
i have the latest version of Core and i too have the same issue as the person above - any help appreciated !

**Comment by Johnnyk56791234** [comment]
apologies I got it working - by deleting the just lines that were recently modified and pasting in the new code, then saving and publishing ... worked - thank God - Core's Back !!!

**Comment by idpaterson** [comment]
I see it was published without a new version number, I'll do an update tomorrow in case anyone else is unable to update from GitHub.

**Comment by Johnnyk56791234** [comment]
thank you for your work , would be lost without Core !!!!!

**Comment by idpaterson** [comment]
All set, if anyone else encounters this issue just be sure to update to the latest version v0.3.16f.20180908.
