### ISSUE TITLE
Feature Request: More than one button per device. 

### ISSUE THREAD

**Issue by DarwinsDen** [ady624/CoRE#8]
Support triggers off of more than one button per device. RM supported 20 buttons per. Great for minimotes and double/triple tap switches. I just did a quick install and test of the app and didn't see it, but if it's already in and I missed it, sorry! 

Awesome work so far btw. Thanks!

**Comment by ady624** [comment]
It's not there yet, but it hasn't been forgotten. I will look into it. I do not own a button device, let alone a multi-button device... but it will get done.

**Comment by ady624** [comment]
Should be working now. If the button DTH sets the numberOfButtons attribute to the number of supported buttons, CoRE will automatically know how many buttons. Otherwise it defaults to 4, until I find a better mechanism for that.
