### ISSUE TITLE
Not possible to fill out if statement

### ISSUE THREAD

**Issue by cl0udninja** [ady624/CoRE#80]
Whenever I I want to create a new piston the if looks like this
![screenshot_20181013-080005](https://user-images.githubusercontent.com/16108706/46907218-1372c280-cec4-11e8-9c50-40f445619b92.png)

**Comment by idpaterson** [comment]
Please update to the latest version of CoRE.

**Comment by cl0udninja** [comment]
🤦‍♂️ I have, but didn't publish. Sorry!

**Comment by idpaterson** [comment]
Thanks for the follow-up! This problem was caused by a ST platform update several weeks ago that required a few very minor changes to the code.

**Comment by cl0udninja** [comment]
No thank you for making this app! It saved me from writing at least two
dozen custom SmartApps! 🙏
