### ISSUE TITLE
Feature Request: Add support for multiple push/text notifications

### ISSUE THREAD

**Issue by Toy4Rick** [ady624/CoRE#9]
Consider any number of numbers by using a delimiter, such as *.  Could be any delimiter really but \* is what many ST users are use to

Thanks, Rick

**Comment by ady624** [comment]
Fixed in next version. Phone numbers can be separated by either of , ; \* |

**Comment by Toy4Rick** [comment]
Simply amazing Adrian.  Your work is greatly appreciated :)

Rick

**Comment by ady624** [comment]
Implemented
